### ISSUE TITLE
cognitive search - ingest coffee menu dataset

### ISSUE THREAD

**Issue by pragmatical** [retaildevcrews/OpenAI-Labs#22]
Create an instance of cognitive search for a product catalog:
https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-search

```[tasklist]
### Tasks
- [x] Create README with az commands to standup an azure cognitive search instance
- [ ] https://github.com/retaildevcrews/OpenAI-Labs/issues/31
- [ ] https://github.com/retaildevcrews/OpenAI-Labs/issues/32
```
